server:
  port: 10500
spring:
  application:
    name: spring-clould-zuul-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/
    ## 配置了以下参数才能在eureka server中发现服务注册
    instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

zuul:
  routes:
    test:
      ## 设置的服务id
      service-id: spring-cloud-client-provider
      path: /t1/**
      retryable: true
      ## true代表去掉path的前缀t1 false代表不需要去掉path的前缀
      strip-prefix: true
    ## 目前默认的可以通过 /spring-cloud-client-provider/test/hello 和 /t1/test/hello访问，如果配置了忽略服务名这第一种方式无法访问
    ignored-services: spring-cloud-user-service-consumer
    ##在所有的router前面添加一个前缀
    prefix:
